### ISSUE TITLE
Media Types are inconsistent

### ISSUE THREAD

**Issue by technosophos** [solo-io/wasm-image-spec#1]
Thanks for putting together this specification. It is clear and succinct. I am confused, though, about the exact media types.

The two defined MTs are:

```
application/vnd.io.wasm.module.config.v1+json
application/vnd.module.wasm.content.layer.v1+wasm
```

However, in the example, the Media Type used for config is different:

```json
[
  {
    "mediaType": "application/vnd.module.wasm.config.v1+json",
    "digest": "sha256:d0a165298ae270c5644be8e9938036a3a7a5191f6be03286c40874d761c18abf",
    "size": 125,
    "annotations": {
      "org.opencontainers.image.title": "runtime-config.json"
    }
  },
  {
    "mediaType": "application/vnd.module.wasm.content.layer.v1+wasm",
    "digest": "sha256:5e82b945b59d03620fb360193753cbd08955e30a658dc51735a0fcbc2163d41c",
    "size": 1043056,
    "annotations": {
      "org.opencontainers.image.title": "filter.wasm"
    }
  }
]
```

Which one is correct? Or am I misunderstanding the text?

**Comment by radu-matei** [comment]
For reference, in Krustlet and `wasm-to-oci` we have been using:

- `application/vnd.wasm.config.v1+json ` for the OCI descriptor
and
- `application/vnd.wasm.content.layer.v1+wasm ` for the actual Wasm content layer.

We should probably investigate the [OCI artifacts guidance for standardizing media types](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md).

**Comment by ilackarms** [comment]
@technosophos thanks for opening this issue! there was a typo in the original spec which has been updated:

`application/vnd.io.wasm.module.config.v1+json` was from the first iteration of the spec and has been replaced by `application/vnd.module.wasm.config.v1+json`
